services:
  backend:
    build: ./backend
    ports:
      - "1111:1111"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:1234@postgres:5432/opencv

  postgres:
    image: postgres:latest
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: opencv

    ports:
      - "5432:5432"
